# Generated by Django 4.2.7 on 2023-12-03 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=20)),
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('llast_name', models.CharField(max_length=20)),
                ('ffaculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.department')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_name', models.CharField(max_length=20)),
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Milestones',
            fields=[
                ('milestone', models.CharField(max_length=100)),
                ('milestone_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RA',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('rA_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.department')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('skill_name', models.CharField(max_length=400)),
                ('skills_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RA_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
                ('skills_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.skills')),
            ],
        ),
        migrations.CreateModel(
            name='RA_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
                ('rA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
            ],
        ),
        migrations.CreateModel(
            name='RA_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.interest')),
                ('rA_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_complete', models.BooleanField()),
                ('milestone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.milestones')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
                ('skills_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.faculty')),
                ('interest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.interest')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects'),
        ),
    ]
