# Generated by Django 5.0 on 2023-12-11 10:50

import django.db.models.deletion
import version1.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=250)),
                ('milestone_description', models.CharField(max_length=250)),
                ('milestone_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('role', models.CharField(max_length=150)),
                ('image', models.ImageField(default='accounts/default.png', upload_to=version1.models.upload_to, verbose_name='image')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.faculty')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.interest')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('completed', models.BooleanField()),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projectmilestones')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='version1.department')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectmilestones',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects'),
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneTaskSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projectmilestones')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects'),
        ),
        migrations.CreateModel(
            name='RA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
            ],
        ),
        migrations.CreateModel(
            name='RA_Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.interest')),
                ('rA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
            ],
        ),
        migrations.CreateModel(
            name='RA_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
                ('rA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
            ],
        ),
        migrations.CreateModel(
            name='RA_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.ra')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.skills')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.skills')),
            ],
        ),
    ]
