# Generated by Django 3.1.3 on 2023-12-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestones',
            name='milestone_complete',
            field=models.BooleanField(default=False),
        ),
    ]
