# Generated by Django 5.0 on 2023-12-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0002_ra_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ra_project',
            name='feedback',
            field=models.CharField(default='N/A', max_length=500),
            preserve_default=False,
        ),
    ]
