# Generated by Django 3.1.3 on 2023-12-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0002_auto_20231203_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='ffaculty_id',
            new_name='faculty_id',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='llast_name',
            new_name='last_name',
        ),
    ]
