# Generated by Django 3.1.3 on 2023-12-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0003_auto_20231203_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='project_id',
            new_name='project',
        ),
    ]
