# Generated by Django 3.1.3 on 2023-12-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0004_auto_20231203_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty_interest',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='faculty_interest',
            old_name='interest_id',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='project_skills',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='project_skills',
            old_name='skills_id',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='projectmilestones',
            old_name='milestone_id',
            new_name='milestone',
        ),
        migrations.RenameField(
            model_name='projectmilestones',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='ra',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='ra',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='ra_interest',
            old_name='interest_id',
            new_name='interest',
        ),
        migrations.RenameField(
            model_name='ra_interest',
            old_name='rA_id',
            new_name='rA',
        ),
        migrations.RenameField(
            model_name='ra_project',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='ra_project',
            old_name='rA_id',
            new_name='rA',
        ),
        migrations.RenameField(
            model_name='ra_skills',
            old_name='rA_id',
            new_name='rA',
        ),
        migrations.RenameField(
            model_name='ra_skills',
            old_name='skills_id',
            new_name='skills',
        ),
    ]
