# Generated by Django 4.2.7 on 2023-12-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0004_alter_customuser_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='department_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='version1.department'),
            preserve_default=False,
        ),
    ]
