# Generated by Django 4.2.7 on 2023-12-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0004_alter_customuser_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='department',
            new_name='user_department',
        ),
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='version1.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MilestoneTaskSerializer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projects')),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projectmilestones')),
            ],
        ),
    ]
