# Generated by Django 4.2.7 on 2023-12-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0005_projects_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='department_id',
            new_name='department',
        ),
    ]
