# Generated by Django 4.2.7 on 2023-12-10 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0005_rename_department_customuser_user_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_department',
            new_name='department',
        ),
    ]
