# Generated by Django 3.1.3 on 2023-12-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0006_projects_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
                ('completed', models.BooleanField()),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.projectmilestones')),
            ],
        ),
    ]
