# Generated by Django 4.2.7 on 2023-12-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('todo', 'To Do'), ('in_review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('anulled', 'Anulled')], default='pending', max_length=20),
        ),
    ]
