# Generated by Django 4.2.7 on 2023-12-04 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0003_milestone_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('todo', 'To Do'), ('in_review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('anulled', 'Anulled')], default='todo', max_length=20)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('todo', 'To Do'), ('in_review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('anulled', 'Anulled')], default='todo', max_length=20)),
                ('hours_required', models.IntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_ra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.projectmilestone')),
            ],
        ),
    ]
