# Generated by Django 4.2.7 on 2023-12-09 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0006_projectteamrequest_projectteaminvitation_projectteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttask',
            old_name='assigned_ra',
            new_name='assignee',
        ),
        migrations.RemoveField(
            model_name='projecttaskfeedback',
            name='target_ra',
        ),
        migrations.AddField(
            model_name='projecttaskfeedback',
            name='reviewer',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttaskfeedback',
            name='target_member',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='target_member', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
