# Generated by Django 4.2.7 on 2023-12-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0007_rename_assigned_ra_projecttask_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_weekly_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
