# Generated by Django 4.2.7 on 2023-12-11 15:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project', '0008_project_estimated_weekly_hours_projectmatch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMatch',
            new_name='ProjectMatchScores',
        ),
    ]
