# Generated by Django 4.2.7 on 2023-12-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_projectmatchscores_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='estimated_weekly_hours',
            new_name='estimated_project_hours',
        ),
    ]
