# Generated by Django 4.2.7 on 2023-12-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='study_area',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Algorithm', 'Algorithm'), ('Computer Engineering', 'Computer Engineering'), ('Cryptography', 'Cryptography'), ('Robotics', 'Robotics'), ('Computer Vision', 'Computer Vision'), ('Software Engineering', 'Software Engineering'), ('Computational Science', 'Computational Science'), ('Numerical Analysis', 'Numerical Analysis'), ('Market Research', 'Market Research'), ('Financial Accounting', 'Financial Accounting'), ('International Trade & Policy', 'International Trade & Policy'), ('Organisational Behaviour', 'Organisational Behaviour'), ('Managerial Behaviour', 'Managerial Behaviour'), ('Marketing', 'Marketing'), ('Operations Management', 'Operations Management'), ('International Finance', 'International Finance'), ('Supply-Chain Management', 'Supply-Chain Management'), ('Business Law', 'Business Law'), ('Competitive Strategy', 'Competitive Strategy'), ('Corporate Finance', 'Corporate Finance'), ('Product Development', 'Product Development')], max_length=100),
        ),
    ]
